# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pr-labeler:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true

  conventional-pr:
    runs-on: ubuntu-latest
    steps: 
    - name: Conventional Pull Request
      uses: CondeNast/conventional-pull-request-action@v0.1.2
      
  comment-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR reviewer
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "Hello there reviewer"
          comment_tag: reviewer


      - name: Comment PR reviewer
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "Hello there author"
          comment_tag: author
          

      - run: echo 'hello ${{ github.event.author }}'
      
      - run: echo '${{ github.event.requested_team }}'
