# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

permissions: read-all


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  conventional-pr:
    runs-on: ubuntu-latest
    steps: 
    - name: Conventional Pull Request
      uses: CondeNast/conventional-pull-request-action@v0.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  commitsar: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch_depth: 0
      - name: Commitsar Action
        uses: aevea/commitsar@v0.20.2
        with:
          config: ${{ github.workspace }}/.commitsar.yaml
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  comment-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' && github.event_name == 'pull_request' }}
    steps:
      - name: Comment PR reviewer
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: | 
            Hello there
          comment_tag: reviewer
          
      - run: echo "event name is:" ${{ github.event_name }} 
      - run: echo "event type is:" ${{ github.event.action }} 
      - run: echo "pull request head sha:" ${{ github.event.pull_request.head.sha }}
      - run: echo "GITHUB_SHA:" ${{ github.sha }} 
      

